color: violet
fieldLayouts:
  e44fe109-c2c3-4a90-a989-8edceaeb5034:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:02:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8c1fefd-226c-43e8-bb74-a962edcca085
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:04:57+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552c46e7-8744-49b9-844e-7362949fd93c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:04:57+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 658f2267-7a72-4d14-831f-a9830a5e0ed2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ccd08a26-3e2d-428f-8c54-4bcd32c4847c
        userCondition: null
handle: categories
hasTitleField: true
icon: fish
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
