color: rose
fieldLayouts:
  316c2f12-8c62-4ba1-8efb-84145f71cf2e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T11:01:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e57c5c0-cabe-4706-982c-ee3defe66ab8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T11:03:24+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66f8c734-fc36-4e24-bd30-481fdde5a12e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b432872-8c90-47ae-932c-a00f0fb1a110
        userCondition: null
handle: locations
hasTitleField: true
icon: anchor
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
