dateModified: 1732273623
email:
  fromEmail: voornaam.naam@howest.be
  fromName: 'Craft Template'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/local'
    type: craft\fs\Local
    url: '@web/local'
meta:
  __names__:
    00b3caa9-4021-43d8-b1d2-866eead44004: Locations # Locations
    0dafb592-6d27-4132-a93b-5eeef2af4dd7: 'List Items' # List Items
    5d45f9f4-7ab7-4459-926d-a8006cad4227: Images # Images
    7e01e965-e32b-450f-8aec-3e8f5c98cde5: Categories # Categories
    10d2260b-dd05-4a49-abb3-800017e15928: 'Craft Template' # Craft Template
    21d6f9ae-1d22-490e-bd89-d6ded5d514ac: 'body text' # body text
    35c35080-108d-485f-925f-407a5ab65a22: Cover # Cover
    68a10d40-1a5d-41af-812e-eebc5c4433d0: Carousel # Carousel
    69c2a9f4-f205-4d68-abed-06fc2fad5e5b: Strenghts # Strenghts
    91a43a30-dd59-47cb-b0b0-4b185f488b9a: Categories # Categories
    955b3b78-0dbd-47ac-9db5-c15151bf0b94: Details # Details
    1094b8b3-5e0b-4264-b997-5e1e4110a127: House # House
    19178fcc-602e-4e2e-a2a4-abf44f2ec6a3: House # House
    94695f2a-c3a1-413b-9104-7237934d049c: Categories # Categories
    1326414a-232b-4fad-8ca2-a80bf0dbb468: Locations # Locations
    1765228e-0ad3-49c0-a7df-f552ada1e942: State # State
    a3917b41-5b9e-455d-82b1-9867d010e228: 'Body Text' # Body Text
    b808e02f-525f-42b2-a4a0-14fceda5c1db: City # City
    bfc5caff-33ac-495a-8336-7abe2887b021: 'Public Schema' # Public Schema
    d3b42bd7-e7fb-4536-8773-1f5957362b49: Price # Price
    e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8: 'Plain Text' # Plain Text
    f6eaef1f-2f88-4856-8eee-c5ae9620f572: 'Craft Template' # Craft Template
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  mapbox:
    edition: standard
    enabled: true
    licenseKey: DIPMY10W2LNZ0N7UG1I9YZ8K
    schemaVersion: 1.1.0
    settings:
      accessToken: null
      enableJsLogging: true
      minifyJsFiles: false
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Template'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
